### ISSUE TITLE
IOS not show toolbar and not edit

### ISSUE THREAD

**Issue by studiozocaro** [xrb21/flutter-html-editor#2]
I have problem in IOS

"flutter: encountered empty header [X-MS-TNEF-Correlator: ]                                                         
        path: satisfied (Path is satisfied), interface: en0                                                        
), error=(null) on <SOConfigurationClient: 0x600000136da0>        "
           
not show toolbar and not edit. I added string in plist.
Help me please

**Comment by xrb21** [comment]
fixed in newer version html_editor: ^1.0.0, try update version

**Comment by studiozocaro** [comment]
after update 
flutter: encountered empty header [X-MS-TNEF-Correlator: ]      
        path: satisfied (Path is satisfied), interface: en0                                                        
flutter: error Error Domain=NSURLErrorDomain Code=-1022 "The resource could not be loaded because the App Transport Security policy requires the use of a secure connection." UserInfo={_NSURLErrorFailingURLSessionTaskErrorKey=LocalDataTask <EF578B21-B4F4-44AC-BC7D-52EB1F133269>.<1>, NSLocalizedDescription=The resource could not be loaded because the App Transport Security policy requires the use of a secure connection., _WKRecoveryAttempterErrorKey=<WKReloadFrameErrorRecoveryAttempter: 0x600002a5c600>, networkTaskDescription=LocalDataTask <EF578B21-B4F4-44AC-BC7D-52EB1F133269>.<1>, NSErrorFailingURLStringKey=http://localhost:5321/packages/html_editor/summernote/summernote.html, NSErrorFailingURLKey=http://localhost:5321/packages/html_editor/summernote/summernote.html, NSUnderlyingError=0x600002488b10 {Error Domain=kCFErrorDomainCFNetwork Code=-1022 "(null)"}}
Syncing files to device iPhone 11...                            11.003ms (!)

**Comment by studiozocaro** [comment]
I have solved it with adding some key in info.plist. The steps I followed are:

Opened my Project target's info.plist file

Added a Key called NSAppTransportSecurity as a Dictionary.

Added a Subkey called NSAllowsArbitraryLoads as Boolean and set its value to YES.

**Comment by MarkStepp** [comment]
> NSAppTransportSecurity  / NSAllowsArbitraryLoads

can you send your exact changes - I tried your suggestion and still getting the same error

**Comment by MarkStepp** [comment]
> fixed in newer version html_editor: ^1.0.0, try update version

Using this version but getting the same error

**Comment by MarkStepp** [comment]
Fixed it - 
```
<key>NSAppTransportSecurity</key>
	<dict>
		<key>NSAllowsArbitraryLoads</key>
		<true/>
	</dict>
```

**Comment by xrb21** [comment]
thanks for your info, now i closed this issue
